version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    # volumes:
    #   - frontend:/app
  backend:
    build: ./api
    ports:
      - "5000:5000"
    # volumes:
    #   - backend:/app
# volumes:
#   frontend:
#   backend: